channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pypdf2=3.0.1
  - nltk=3.7
  - fuzzywuzzy=0.18.0
  - python-levenshtein=0.12.2
  - pip
  - pip:
    - python-Levenshtein==0.12.2
